### ISSUE TITLE
Powershell Task

### ISSUE THREAD

**Issue by dhruvchand** [microsoft/devcenter-catalog#2]
Run a linked powershell script as a Dev Box customization task 

**Describe the solution you'd like**
As a user, I should be able to:

- Specify a single line or multi-line powershell script "inline" 
- This will only run during provisioning (and not at login)

Sample usage:
```
setupTasks:

  - task: powershell
    inputs:
      command: "Run-Powershell var1 var2"

```
