### ISSUE TITLE
Enable Windows Feature Task

### ISSUE THREAD

**Issue by dhruvchand** [microsoft/devcenter-catalog#3]
**Is your feature request related to a problem? Please describe.**
Provide an easy way to enable or disable specific Windows features

**Describe the solution you'd like**
As a user, I should be able to:

- Specify the standard name for a windows feature

``` 
setupTasks:
  - task: Add-WindowsFeature
    inputs:
      features:
      - "featureName"
      - "featureName"
      - "featureName"
    
setupTasks:
  - task: Add-WindowsFeature
    inputs:
      features: "featureName"

```
