### ISSUE TITLE
Install packages using Choco

### ISSUE THREAD

**Issue by dhruvchand** [microsoft/devcenter-catalog#5]
Is your feature request related to a problem? Please describe.
I would like to automate installation of packages through choco

Describe the solution you'd like
As a user, I should be able to:

- Install packages by providing a list of package names and version names:
- as a list as package@version, with version as optional (pick latest)
- For each package, I should be able to specify: additionalOptions that are passed through to choco

other requirements:
- accept all licenses (yes to all) by default
- install choco if not present

For v1, we will NOT support using a config file. 
we can print out that by using this task, you are accepting licenses
we will only support additional options. 

```
setupTasks:
 - task: choco
    inputs:
      package: "packageName@version"
      additionalOptions: "--key val"

```
