### ISSUE TITLE
Clone repo 

### ISSUE THREAD

**Issue by dhruvchand** [microsoft/devcenter-catalog#6]
**Is your feature request related to a problem? Please describe.**
I would like to clone a repo I have access to

**Describe the solution you'd like**
parameters to support:
1. src repo url
2. clone to directory
3. params to pass to git clone

Support for repo sources:
1. github
2. ADO

pre-requisites: 
If git and GCM (>= GCM 2.1..2,) are not installed, install them first. We should check if PATH already contains git and GCM. If yes, but older versions: overwrite with supported git and gcm version. 

```
setupTasks:
  - task: clone-repository-on-login
    inputs:
      src: "repo-url"
      cloneTo: "./path/"
      additionalOptions: "--flag --key val"
```
