### ISSUE TITLE
Add VS Code Extension

### ISSUE THREAD

**Issue by dhruvchand** [microsoft/devcenter-catalog#7]
**Is your feature request related to a problem? Please describe.**
I would like to have my VS code extensions installed when I receive my Dev Box

**Describe the solution you'd like**
As a user, I should be able to:
1. specify a list of extensions (extension version optional) that ought to be installed on my Dev Box, using
2. extension id
3. path to file that contains export of code --list-extensions
```
setupTasks:

 - task: install-vscode-extension
    inputs:
      extension: "packageName@version "
      additionalOptions: 
```

For V1, we will NOT be supporting path to a JSON export of extensions from VS Code
```
 - task: install-vscode-extension
    inputs:
      extensions: "path/to/extension/list/export"
      additionalOptions: 

```
