### ISSUE TITLE
Install Visual Studio Extension

### ISSUE THREAD

**Issue by dhruvchand** [microsoft/devcenter-catalog#8]
**Is your feature request related to a problem? Please describe.**
I would like to have my VS extensions installed when I receive my Dev Box

**Describe the solution you'd like**
As a user, I should be able to:
1. specify a list of extensions (extension version optional) that ought to be installed on my Dev Box, using a list of packageNames from the VS marketplace

```
setupTasks:

 - task: install-vs-extension
    inputs:
      extension: "packageName@version"

```

For v1, we will NOT support path to json exports of extensions
```
 - task: install-vs-extension
    inputs:
      extensions: "/path/to/vsixt"

```
